name: Set Secret Key

on: [push]

jobs:
  set-secret-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set secret key
      run: |
        for file in $(find . -type f -name '*.html'); do
          sed -i 's/SECRET_KEY_PLACEHOLDER/k-14hu18/g' "$file"
        done
